# .github/workflows/security.yml

name: MCP Security

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"  # nightly drift scan at 3:00 AM UTC

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pipx and mcp-scan
        run: |
          python3 -m pip install --upgrade pipx
          pipx ensurepath
          pipx install mcp-scan

      - name: Run MCP Scan
        run: mcp-scan scan ./mcp-servers/. --storage-file results.json

      - name: Fail on High Findings
        run: |
          HIGH=$(jq '.summary.high' results.json)
          if [ "$HIGH" -ne 0 ]; then
            echo "$HIGH high findings"
            exit 1
          fi
